config/routes.rb
Rails.application.routes.draw do

  resources :followings, only: [:index, :create, :destroy]
  # get 'comments/create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get 'users/search', to: "users#index"

  resources :users, only: [:index,:show,:edit]

  #to ensure that user can only edit own profile - ie. no id param in route
  get 'users/profile/edit', to: "users#edit"
  post 'users/profile/update', to: 'users#update'
  #for image upload
  patch 'users/profile/update_image', to: 'users#update_image'
  get 'events/:id/join', to: 'attendings#redirection'
  post 'events/:id/join', as: 'join_event', to: 'attendings#join'
  delete 'events/:id/leave', as: 'leave_event', to: 'attendings#leave'
  get 'events/list', as: 'list_event', to: 'events#list'
  get 'events/list/recommend', as: 'recommend_event', to: 'events#recommend'
  get 'events/list/myevents', as: 'myevents', to: 'events#myevents'
  root to: 'events#index'
  resources :event_tags
  resources :events do
    resources :comments
  end
  #contact is just a test controller because cannot render view without it
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_event
  before_action :find_comment, only: [:destroy, :edit, :update, :comment_owner]
  before_action :comment_owner, only: [:destroy, :edit, :update]

  def create

    @comment = @event.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save!

    respond_to do |format|
      format.html { redirect_to @event }
      format.js #by default, render comments/create.js.erb
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @event }
      format.js
    end
  end

  def edit

  end

  def update
    if @comment.update(params[:comment].permit(:message))
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end

  private

  def find_event
    @event = Event.find(params[:event_id])
  end

  def find_comment
    @comment = @event.comments.find(params[:id])
  end

  def comment_owner
    unless current_user.id == @comment.user_id
      flash[:notice] = "You have no access"
      redirect_to @event
    end
  end

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id="comment-<%= comment.id %>" class="deleteme">
  <%= comment.user.email %> says:
  <p><%= comment.message %></p>

  <% if current_user == comment.user %>
    <%= link_to "Delete comment", [comment.event, comment], id: "comment-delete", remote: true, method: :delete %>
    <%= link_to "Edit comment", edit_event_comment_path(comment.event, comment) %><br><br>
  <% end %>
</li>

app/views/comments/_form.html.erb
<%= form_for [@event, @event.comments.new], remote: true do |f| %>
                                              <!-- ^ available for link_to and button_to -->
  <%= f.text_area :message, placeholder: "Write a comment..." %>
  <%= f.submit 'Post Comment', class: 'button' %>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/create.js.erb
$('#comments').append("<%= j render @comment %>");                                      // semicolon at the end cuz this is js not CoffeeScript

app/views/comments/edit.html.erb
<%= form_for([@event, @comment]) do |f| %>
  <%= f.text_area :message %>
  <%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.message %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @comment.message %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>