config/routes.rb
Rails.application.routes.draw do

  resources :followings, only: [:index, :create, :destroy]
  # get 'comments/create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get 'users/search', to: "users#index"

  resources :users, only: [:index,:show,:edit]

  #to ensure that user can only edit own profile - ie. no id param in route
  get 'users/profile/edit', to: "users#edit"
  post 'users/profile/update', to: 'users#update'
  #for image upload
  patch 'users/profile/update_image', to: 'users#update_image'
  get 'events/:id/join', to: 'attendings#redirection'
  post 'events/:id/join', as: 'join_event', to: 'attendings#join'
  delete 'events/:id/leave', as: 'leave_event', to: 'attendings#leave'
  get 'events/list', as: 'list_event', to: 'events#list'
  get 'events/list/recommend', as: 'recommend_event', to: 'events#recommend'
  get 'events/list/myevents', as: 'myevents', to: 'events#myevents'
  root to: 'events#index'
  resources :event_tags
  resources :events do
    resources :comments
  end
  #contact is just a test controller because cannot render view without it
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:facebook]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        #  , :confirmable


  has_many :followings, dependent: :destroy
  has_many :followers, :through => :following
  has_many :attendings
  has_many :events, :through => :attendings
  has_many :comments, dependent: :destroy

  has_many :interests
  has_many :tags, :through => :interests


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name. model no name field currently
      user.image = auth.info.image # assuming the user model has an image
      user.name = auth.info.name
      user.first_name = auth.extra.raw_info.first_name
      user.last_name = auth.extra.raw_info.last_name
      user.min_age = auth.extra.raw_info.age_range.min.last
      user.gender = auth.extra.raw_info.gender
      user.birthday = Date.strptime(auth.extra.raw_info.birthday,'%m/%d/%Y')
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end



end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to events_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show,:edit,:update]
  skip_before_action :verify_authenticity_token, :only => [:update]

  def index
    if current_user
      @users = User.where(["first_name LIKE ?", "%#{params[:search]}%"]).where.not(id: current_user.id)
      @users += User.where(["email LIKE ?", "%#{params[:search]}%"]).where.not(id: current_user.id)
      @users += User.where(["name LIKE ?", "%#{params[:search]}%"]).where.not(id: current_user.id)

      @usersfilter = @users.pluck(:id)
      @follow = Following.where(:follower_id => @usersfilter, :user_id => current_user.id) #produces an array of entries of people the current user is following
      @hash_of_follower_id_and_follow_id = Hash[@follow.map{ |c| [c.follower_id, c.id] }]
      @following = Following.new

    else
      @users = User.where(["first_name LIKE ?", "%#{params[:search]}%"])
      @users += User.where(["email LIKE ?", "%#{params[:search]}%"])
      @users += User.where(["name LIKE ?", "%#{params[:search]}%"])
      @not_signed_in = true
    end
    @events = Event.where(["name LIKE ?", "%#{params[:search]}%"])
    @events += Event.where(["description LIKE ?", "%#{params[:search]}%"])
  end


  def show

    @user = User.find_by_id(params[:id])
    #to see if truthie or falsie -> if current user already follow
    @follow = Following.where(:follower_id => params[:id], :user_id => current_user.id).first
    @following = Following.new

    current_following_records = @user.followings.select('follower_id')
    current_follower_records = Following.where(:follower_id => @user.id).select('user_id')

    @current_followings = User.where(:id => current_following_records)
    @current_followers = User.where(:id => current_follower_records)

    # render :show -> auto show by controller
  end

  def edit
    @user = User.find(current_user.id)
    render :edit
  end

  def update
   @user = User.find(current_user.id)
   name = user_params["name"]
   value = user_params["value"]
   @user.update(name => value)

    if @user.save
     flash[:success] = "user successfully updated!"
    else
      flash[:warning] = "user failed to update!"
    end
    redirect_to users_profile_edit_path
  end

  def update_image
    @user = User.find(current_user.id)
    image = Cloudinary::Uploader.upload(image_params["image"])
    @user.update("image" => image["url"])
    if @user.save
      flash[:success] = "user profile picture updated!"
    else
      flash[:warning] = "user picture failed to update!"
    end
    redirect_to users_profile_edit_path
  end

  private
  def user_params
    params.permit(:name,:value,:pk)
  end

  def image_params
    params["user"]
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10">
      <h1 class="">Name:
        <a href="#" data-url= <%= users_profile_update_path %> id="name" data-type="text" data-pk="1" data-title="name">
          <% if @user.name == nil %>
          <%= "please enter name" %>
          <% else %>
          <%= @user.name %>
          <% end %>
        </a>
      </h1>

      <br>
    </div>

    <div class="col-sm-2"><a href="/users" class="pull-right"><img title="profile image" class="img-circle img-responsive" src= <%= @user.image %> ></a>
      <%= bootstrap_form_for @user, url: {action: "update_image"} do |f| %>
        <%= f.file_field :image, label: "select image" %>
        <%= f.submit "upload image" %>
      <% end %>
    </div>



  </div>
  <br
  <div class="row">
    <div class="col-sm-3">
      <!--left col-->
      <ul class="list-group">
          <li class="list-group-item text-muted" contenteditable="false">Profile</li>
          <li class="list-group-item text-right"><span class="pull-left"><strong class="">Joined</strong></span><%= @user.created_at.strftime("%d %B %Y") %></li>
          <li class="list-group-item text-right"><span class="pull-left"><strong class="">Last seen</strong></span><%= @user.last_sign_in_at.strftime("%d %B %Y") %></li>
          <li class="list-group-item text-right"><span class="pull-left"><strong class="">Real name</strong></span><%= @user.name %></li>
          <li class="list-group-item text-right"><span class="pull-left"><strong class="">Events Attended: </strong></span><%= @user.events.length %></li>
          <li class="list-group-item text-right"><span class="pull-left"><strong class="">Events Created: </strong></span><%= @user.events.length %></li>
      </ul>

      <div class="panel panel-default">
        <div class="panel-heading">Insured / Bonded?</div>
        <div class="panel-body"><i style="color:green" class="fa fa-check-square"></i> Yes, I am insured and bonded.</div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Website <i class="fa fa-link fa-1x"></i></div>
        <div class="panel-body"><a href="http://bootply.com" class="">bootply.com</a></div>
      </div>

      <ul class="list-group">
        <li class="list-group-item text-muted">Activity <i class="fa fa-dashboard fa-1x"></i></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong class="">Shares</strong></span> 125</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong class="">Likes</strong></span> 13</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong class="">Posts</strong></span> 37</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong class="">Followers</strong></span> 78</li>
      </ul>

      <div class="panel panel-default">
        <div class="panel-heading">Social Media</div>
        <div class="panel-body"><i class="fa fa-facebook fa-2x"></i>  <i class="fa fa-github fa-2x"></i>
          <i class="fa fa-twitter fa-2x"></i> <i class="fa fa-pinterest fa-2x"></i>  <i class="fa fa-google-plus fa-2x"></i>
        </div>
      </div>
    </div>

      <!--/col-3-->

    <div class="col-sm-9" contenteditable="false" style="">
      <div class="panel panel-default">
        <div class="panel-heading"><%= @user.name %>'s Bio</div>
        <div class="panel-body"><%= @user.name %></div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">Interests</div>
        <div class="panel-body">
          <!-- <a href="#" id="type_of_sport" data-type="select2" data-pk="1" data-title="Enter username" class="editable editable-click">superuser</a> -->
          <!-- <a href="#" id="country" data-type="select2" data-pk="1" data-value="ru" data-url="/post" data-title="Select country"></a> -->
          <a href="#" id="tags" data-type="select2" data-pk="1" data-title="Enter tags" class="editable editable-click" style="display: inline;">html, javascript</a>
        </div>
        <!-- <h1 class="">Interests:
          <a href="#" data-url= <%= users_profile_update_path %> id="sports" data-type="text" data-pk="1" data-title="sports">
            <% if @user.name == nil %>
            <%= "please enter name" %>
            <% else %>
            <%= @user.name %>
            <% end %>
          </a>
        </h1> -->
      </div>

      <div class="panel panel-default target">
        <div class="panel-heading" contenteditable="false">Recent Activities Joined</div>
        <div class="panel-body">
          <div class="row">


              <% @user.events.each_with_index do | value, index | %>
              <% if index % 3 == 0 %>
                <div class="row text-center">
              <% end %>
                  <div class="col-md-4 col-sm-6 hero-feature">
                      <div class="thumbnail">
                          <img src="http://placehold.it/800x500" alt="">
                          <div class="caption">
                              <h3> <%= value.name %> </h3>
                              <p> Sport: <%= value.type_of_sport %> </p>

                              <p> Date: <%= value.date.to_formatted_s(:long) %> </p>
                              <p> Time: <%= value.time.to_formatted_s(:time) %> </p>
                              <p> Location: <%= value.location %> </p>
                              <% counter = 0 %>
                              <% value.attendings.each_with_index do |x, y| %>
                                <% if current_user != nil && x.user_id == current_user.id %>
                                <%= link_to "Leave", leave_event_path(value), :method=> :delete, :class=>"btn btn-primary" %>
                                <% counter = 1 %>
                                <% elsif y == value.attendings.length - 1 && counter == 0%>
                                <%= link_to "Join Now!", join_event_path(value), :method=> :post, :class=>"btn btn-primary" %>
                                <% end %>
                              <% end %>
                               <%= link_to "More Info", event_path(value), { :class=>"btn btn-default" } %>
                          </div>
                      </div>
                  </div>
              <% if index % 3 == 2 || @user.events.length - 1 == index %>
                </div>
              <% end %>
            <% end %>

          </div>
        </div>
        <!-- end row -->
      </div>
    </div>
  </div>
</div>

<!-- script for x-editable -->
<script
  src="https://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<%= javascript_include_tag "select2.min.js" %>

<script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>

<script>
  $.fn.editable.defaults.mode = 'inline';
    $('#name').editable();
    // $('#type_of_sport').editable({
    //     inputclass: 'input-large',
    //     select2: {
    //       tags: true,
    //         data: ['html', 'javascript', 'css', 'ajax'],
    //         tokenSeparators: [",", " "]
    //     }
    // });

    //local source
    $('#country').editable({
        source: [
              {id: 'gb', text: 'Great Britain'},
              {id: 'us', text: 'United States'},
              {id: 'ru', text: 'Russia'}
           ],
        select2: {
           multiple: true
        }
    });
    //remote source (simple)
    $('#country').editable({
        source: '/getCountries',
        select2: {
            placeholder: 'Select Country',
            minimumInputLength: 1
        }
    });
    //remote source (advanced)
    $('#country').editable({
        select2: {
            placeholder: 'Select Country',
            allowClear: true,
            minimumInputLength: 3,
            id: function (item) {
                return item.CountryId;
            },
            ajax: {
                url: '/getCountries',
                dataType: 'json',
                data: function (term, page) {
                    return { query: term };
                },
                results: function (data, page) {
                    return { results: data };
                }
            },
            formatResult: function (item) {
                return item.CountryName;
            },
            formatSelection: function (item) {
                return item.CountryName;
            },
            initSelection: function (element, callback) {
                return $.get('/getCountryById', { query: element.val() }, function (data) {
                    callback(data);
                });
            }
        }
    });

</script>

app/views/users/index.html.erb
<!-- Page Content -->
  <div class="container">
        <!-- Title -->
    <div class="row">
      <div class="col-lg-10">
        <div class="row">
          <div class="col-lg-12">
            <h2>Search results:</a></h2>
            <h3>Users found:</h3>
            <% if @users == [] %>
              <h4> No users found! </h4>
            <% end %>
          </div>
        </div>
        <% @users.each_with_index do | value, index | %>
          <% if index % 4 == 0 %>
            <div class="row text-center">
          <% end %>
              <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                  <img src="http://lorempixel.com/800/500/" alt="">
                    <div class="caption">
                      <% results_name = value.name || "NIL" %>
                      <h3>Name: <%= link_to "#{results_name}", user_path(value.id) %> </h3>
                      <% results_joined = value.created_at.to_formatted_s(:long)|| "NIL" %>
                      <p>Joined at <%= results_joined %> </p>
                      <% if current_user == nil %>
                        <%= form_for(@following, :url => followings_path, :method => 'post') do |f| %>
                          <div class="actions">
                            <%= f.hidden_field :follower_id, value: value.id  %>
                            <%= f.submit 'follow me', :class => 'btn btn-default' %>
                          </div>
                        <% end %>
                      <% else %>
                        <% if value.id != current_user.id &&  @follow ==nil %>
                          <%= form_for(@following, :url => followings_path, :method => 'post') do |f| %>
                            <div class="actions">
                              <%= f.hidden_field :follower_id, value: value.id  %>
                              <%= f.submit 'follow me', :class => 'btn btn-default' %>
                            </div>
                          <% end %>
                          <% unless @not_signed_in %>
                            <% if value.id != current_user.id &&  @hash_of_follower_id_and_follow_id[value.id] == nil %>
                              <%= form_for(@following, :url => followings_path, :method => 'post') do |f| %>
                                <div class="actions">
                                  <%= f.hidden_field :follower_id, value: value.id  %>
                                  <%= f.submit 'follow me', :class => 'btn btn-default' %>
                                </div>
                              <% end %>
                            <% elsif value.id != current_user.id && @hash_of_follower_id_and_follow_id[value.id] %>
                              <div class="label label-primary">Followed!!</div>
                              <%= form_for(@following, :url => following_path(@hash_of_follower_id_and_follow_id[value.id]), :method => 'delete') do |f| %>
                                <div class="actions">
                                  <%= f.hidden_field :follower_id, value: value.id  %>
                                  <%= f.submit 'unfollow me', :class => 'btn btn-default' %>
                                </div>
                              <% end %>
                            <% end %>
                          <% end %> <!-- for unless -->
                        <% end %> <!-- for if -->
                      <% end %> <!-- for if current user = nil -->
                    </div>
                </div>
              </div>
          <% if index % 4 == 3 || @users.length - 1 == index %>
            </div>
          <% end %>
        <% end %> <!-- for users.each_with_index do; end of user search results section -->

        <hr>

        <% if @events != nil %>
          <div class="row">
            <div class="col-lg-12">
              <h3>Events found:</h3>
              <% if @events == [] %>
                <h4> No events found! </h4>
              <% end %>
            </div>
          </div>
          <% @events.each_with_index do | value, index | %>
            <% if index % 4 == 0 %>
              <div class="row text-center">
            <% end %>
                <div class="col-md-3 col-sm-6 hero-feature">
                  <div class="thumbnail">
                    <img src="http://lorempixel.com/800/500/" alt="">
                    <div class="caption">
                      <% results_name = value.name || "NIL" %>
                      <h3>Name: <%= link_to "#{results_name}", event_path(value.id) %> </h3>
                      <% results_joined = value.created_at.to_formatted_s(:long)|| "NIL" %>
                      <p>Created at <%= results_joined %> </p>
                    </div>
                  </div>
                </div>
            <% if index % 4 == 3 || @events.length - 1 == index %>
              </div>
            <% end %>
          <% end %>
        <hr>
        <% end %> <!-- for if events not equals to nil -->
      </div>
    </div>

    <footer>
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright &copy; Your Website 2014</p>
        </div>
      </div>
    </footer>

  </div>

app/views/users/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col-sm-10">
        <h1 class=""><%= @user.name %></h1>
        <% if @user.id != current_user.id &&  @follow ==nil %>
          <%= form_for(@following, :url => followings_path, :method => 'post') do |f| %>
          <div class="actions">
            <%= f.hidden_field :follower_id, value: @user.id  %>
            <%= f.submit 'follow me', :class => 'btn btn-default' %>
          </div>
          <% end %>

        <% elsif @user.id != current_user.id && @follow !=nil %>
          <div class="label label-primary">Followed!!</div>
          <!-- unfollow link -->
          <%= form_for(@following, :url => following_path(@follow.id), :method => 'delete') do |f| %>
          <div class="actions">
            <%= f.hidden_field :follower_id, value: @user.id  %>
            <%= f.submit 'unfollow me', :class => 'btn btn-default' %>
          </div>
          <% end %>
        <% else %>
          <%= link_to "edit", users_profile_edit_path, { :class=>"btn btn-default" } %>
        <% end %>
        <br>
      </div>

      <div class="col-sm-2"><img title="profile image" class="img-circle img-responsive" src= <%= @user.image %> >
      </div>
    </div>
    <br
    <div class="row">
      <div class="col-sm-3">
        <!--left col-->
        <ul class="list-group">
            <li class="list-group-item text-muted" contenteditable="false">Profile</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong class="">Joined</strong></span><%= @user.created_at.strftime("%d %B %Y") %></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong class="">Last seen</strong></span><%= @user.last_sign_in_at.strftime("%d %B %Y") %></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong class="">Real name</strong></span><%= @user.name %></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong class="">Events Attended: </strong></span><%= @user.events.length %></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong class="">Events Created: </strong></span><%= @user.events.length %></li>
        </ul>

        <div class="panel panel-default">
          <div class="panel-heading">Insured / Bonded?</div>
          <div class="panel-body"><i style="color:green" class="fa fa-check-square"></i> Yes, I am insured and bonded.</div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">Website <i class="fa fa-link fa-1x"></i></div>
          <div class="panel-body"><a href="http://bootply.com" class="">bootply.com</a></div>
        </div>

        <ul class="list-group">
          <li class="list-group-item text-muted">Activity <i class="fa fa-dashboard fa-1x"></i></li>
          <li class="list-group-item text-right"><span class="pull-left"><strong class="">Shares</strong></span> 125</li>
          <li class="list-group-item text-right"><span class="pull-left"><strong class="">Likes</strong></span> 13</li>
          <li class="list-group-item text-right"><span class="pull-left"><strong class="">Posts</strong></span> 37</li>
          <li class="list-group-item text-right"><span class="pull-left"><strong class="">Followers</strong></span> 78</li>
        </ul>

        <div class="panel panel-default">
          <div class="panel-heading">Social Media</div>
          <div class="panel-body"><i class="fa fa-facebook fa-2x"></i>  <i class="fa fa-github fa-2x"></i>
            <i class="fa fa-twitter fa-2x"></i> <i class="fa fa-pinterest fa-2x"></i>  <i class="fa fa-google-plus fa-2x"></i>
          </div>
        </div>
      </div>

        <!--/col-3-->

      <div class="col-sm-9" contenteditable="false" style="">
        <div class="panel panel-default">
          <div class="panel-heading"><%= @user.name %>'s Bio</div>
          <div class="panel-body"><%= @user.name %></div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">Interests</div>
          <div class="panel-body">
            <ul>

            </ul>
          </div>
        </div>

        <div class="panel panel-default target">
          <div class="panel-heading" contenteditable="false">Recent Activities Joined</div>
          <div class="panel-body">
            <div class="row">

                <% @user.events.each_with_index do | value, index | %>
                <% if index % 3 == 0 %>
                  <div class="row text-center">
                <% end %>
                    <div class="col-md-4 col-sm-6 hero-feature">
                        <div class="thumbnail">
                            <img src="http://lorempixel.com/800/500/" alt="">
                            <div class="caption">
                                <h3> <%= value.name %> </h3>
                                <p> Sport: <%= value.type_of_sport %> </p>
                                <p> Date: <%= value.date.to_formatted_s(:long) %> </p>
                                <p> Time: <%= value.time.to_formatted_s(:time) %> </p>
                                <p> Location: <%= value.location %> </p>
                                <% counter = 0 %>
                                <% value.attendings.each_with_index do |x, y| %>
                                  <% if current_user != nil && x.user_id == current_user.id %>
                                  <%= link_to "Leave", leave_event_path(value), :method=> :delete, :class=>"btn btn-primary" %>
                                  <% counter = 1 %>
                                  <% elsif y == value.attendings.length - 1 && counter == 0%>
                                  <%= link_to "Join Now!", join_event_path(value), :method=> :post, :class=>"btn btn-primary" %>
                                  <% end %>
                                <% end %>
                                 <%= link_to "More Info", event_path(value), { :class=>"btn btn-default" } %>
                            </div>
                        </div>
                    </div>
                <% if index % 3 == 2 || @user.events.length - 1 == index %>
                  </div>
                <% end %>
              <% end %>

            </div>
          </div>
          <!-- end row -->
        </div>

        <div class="panel panel-default target">
          <div class="panel-heading" contenteditable="false">Currently Following</div>
          <div class="panel-body">
            <div class="row">
              <% @current_followings.each do |x| %>
              <div class="col-md-2 col-sm-4 hero-feature">
                  <div class="thumbnail text-center">
                    <%= link_to(x) do %>
                    <img src= <%= x.image %> alt="">
                    <div class="caption">
                        <h5><%= x.name %></h5>
                    </div>
                    <% end %>
                  </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>

        <div class="panel panel-default target">
          <div class="panel-heading" contenteditable="false">Current Followers</div>
          <div class="panel-body">
            <div class="row">
              <% @current_followers.each do |x| %>
              <div class="col-md-2 col-sm-4 hero-feature">
                  <div class="thumbnail text-center">

                    <%= link_to(x) do %>
                    <img src= <%= x.image %> alt="">
                    <div class="caption">
                        <h5><%= x.name %></h5>
                    </div>
                    <% end %>

                  </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>


      </div>
    </div>
  </div>