config/routes.rb
Rails.application.routes.draw do

  resources :followings, only: [:index, :create, :destroy]
  # get 'comments/create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get 'users/search', to: "users#index"

  resources :users, only: [:index,:show,:edit]

  #to ensure that user can only edit own profile - ie. no id param in route
  get 'users/profile/edit', to: "users#edit"
  post 'users/profile/update', to: 'users#update'
  #for image upload
  patch 'users/profile/update_image', to: 'users#update_image'
  get 'events/:id/join', to: 'attendings#redirection'
  post 'events/:id/join', as: 'join_event', to: 'attendings#join'
  delete 'events/:id/leave', as: 'leave_event', to: 'attendings#leave'
  get 'events/list', as: 'list_event', to: 'events#list'
  get 'events/list/recommend', as: 'recommend_event', to: 'events#recommend'
  get 'events/list/myevents', as: 'myevents', to: 'events#myevents'
  root to: 'events#index'
  resources :event_tags
  resources :events do
    resources :comments
  end
  #contact is just a test controller because cannot render view without it
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :date, :time, :minpax, :maxpax, presence: true

  has_many :attendings, dependent: :destroy
  has_many :users, :through => :attendings
  has_many :comments, dependent: :destroy

  has_many :event_tags
  has_many :tags, :through => :event_tags
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :recommend, :myevents]
  # before_action :list_attending, only: [:index]
  def index
    if current_user == nil
      if params[:date]
        @latestevents = Event.where("date >= ?", params[:date]).first(4)
        @myevents = nil
      else
        @latestevents = Event.all.order('created_at DESC').first(4)
        @myevents = nil
      end
    else
      if params[:date]
        @latestevents = Event.all.where.not(user_id: current_user.id).where("date >= ?", params[:date]).order('created_at DESC').first(4)
      elsif params[:region]
        puts "YESSSSSSSSSSSSSSSSSSKTKEPOOSDJBSB"
        @latestevents = Event.where("region = ?", params[:region])
      else
        @latestevents = Event.all.where.not(user_id: current_user.id).order('created_at DESC').first(4)
      end
        @myevents = Event.all.where(user_id: current_user.id).order('created_at DESC').first(4)
    end
    @events_by_date = @latestevents.group_by(&:date)
    @date = params[:datedisplay] ? Date.parse(params[:datedisplay]) : Date.today
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    if @event.save
      EventTag.create(tag_id: @event.region, event_id: @event.id)
      EventTag.create(tag_id: @event.location, event_id: @event.id)
      EventTag.create(tag_id: @event.type_of_sport, event_id: @event.id)
      flash[:success] = "Event created successfully!"
      redirect_to join_event_path(@event.id)
    else
      flash[:danger] = @event.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @event = Event.find_by_id(params[:id])
    @comments = Comment.where(event_id: @event).order("created_at ASC")
  end

  def list
    if current_user == nil
      @event = Event.all.order('created_at DESC')
      @check = 1
    else
      @event = Event.all.where.not(user_id: current_user.id).order('created_at DESC')
      @check = 1
    end
    @tag = Tag.all

  end

  def recommend
    @filter = Attending.all.where(user_id: current_user.id).select(:event_id).pluck(:event_id)
    @follow = Following.all.where(user_id: current_user.id).select(:follower_id)
    @recommend = Attending.all.where(user_id: @follow).select(:event_id)
    @event = Event.all.where.not(user_id: current_user.id, id: @filter).where(id: @recommend).order('created_at DESC')
    @tag = Tag.all
    @check = 2
    render :list

  end

  def myevents
    @event = Event.all.where(user_id: current_user.id)
    @tag = Tag.all
    @check = 3
    render :list

  end

  private

  def event_params
    params.require(:event).permit(:user_id, :name, :description, :region, :location, :type_of_sport, :date, :time, :duration, :minpax, :maxpax)
  end

  # def list_attending
  #   @list = Attending.find_by_user_id(current_user.id)
  # end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<% @following %>
<% @event.each do |value| %>
<div class="row">
    <div class="col-md-7">
        <a href="#">
            <img class="img-responsive" src="http://lorempixel.com/700/300/" alt="">
        </a>
    </div>
    <div class="col-md-5">
        <h3 style="color: white"><%= value.name %></h3>
        <% @tag.where(id: value.location).each do |location| %>
        <h4 style="color: white"><%= location.value %></h4>
        <% end %>
        <p style="color: white"><%= value.description %></p>
        <a class="btn btn-primary" href=<%= event_path(value) %>> Details <span class="glyphicon glyphicon-chevron-right"></span></a>
    </div>
</div>
<hr>
<% end %>

app/views/events/filter.js.erb
$(function() {
  $("#region_form").change(function() {
    this.submit()
  })
})

app/views/events/index.html.erb
<!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron hero-spacer">
            <h1>sportING</h1>
            <p>Sport meetups with like-minded people, at your fingertips.</p>
            <div class="row">
              <%= link_to "Create Events", new_event_path, { :class=>"btn btn-dax btn-large" } %>
              <%= link_to "Show Events", list_event_path, { :class=>"btn btn-dax btn-large" } %>
            </div>
        </header>

        <hr>

        <!-- Title -->
        <div class="row">
        <div class="col-lg-10">
        <div class="row">
            <div class="col-lg-12">
                <h3><a href=<%= list_event_path %>>Latest Events</a></h3>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <% @latestevents.each_with_index do | value, index | %>
          <% if index % 4 == 0 %>
            <div class="row text-center">
          <% end %>
              <div class="col-md-3 col-sm-6 hero-feature">
                  <div class="thumbnail">
                      <img src="http://lorempixel.com/800/500/" alt="">
                      <div class="caption">
                          <h3> <%= value.name %> </h3>
                          <p> Sport: <%= value.tags.where("tag_id = ?", "#{value.type_of_sport}").first.value %> </p>

                          <p> Date: <%= value.date.to_formatted_s(:long) %> </p>
                          <p> Time: <%= value.time.to_formatted_s(:time) %> </p>
                          <p> Region: <%= value.tags.where("tag_id = ?", "#{value.region}").first.value %> </p>
                          <p> Location: <%= value.tags.where("tag_id = ?", "#{value.location}").first.value %> </p>
                          <% counter = 0 %>
                          <% value.attendings.each_with_index do |x, y| %>
                            <% if current_user != nil && x.user_id == current_user.id %>
                            <%= link_to "Leave", leave_event_path(value), :method=> :delete, :class=>"btn btn-primary" %>
                            <% counter = 1 %>
                            <% elsif y == value.attendings.length - 1 && counter == 0%>
                            <% if value.attendings.length == value.maxpax %>
                            <button class="btn btn-static"> Full </button>
                            <% else %>
                            <%= link_to "Join Now!", join_event_path(value), :method=> :post, :class=>"btn btn-primary" %>
                            <% end %>
                            <% end %>
                          <% end %>
                           <%= link_to "More Info", event_path(value), { :class=>"btn btn-default" } %>
                      </div>
                  </div>
              </div>
          <% if index % 4 == 3 || @latestevents.length - 1 == index %>
            </div>
          <% end %>
        <% end %>
        <!-- /.row -->
        <hr>
        <% if @myevents != nil && !@myevents.empty? %>
        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3><a href=<%= user_path(current_user.id) %>>My Events</a></h3>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <% @myevents.each_with_index do | value, index | %>
          <% if index % 4 == 0 %>
            <div class="row text-center">
          <% end %>
              <div class="col-md-3 col-sm-6 hero-feature">
                  <div class="thumbnail">
                      <img src="http://lorempixel.com/800/500/" alt="">
                      <div class="caption">
                          <h3> <%= value.name %> </h3>
                          <p> Sport: <%= value.tags.where("tag_id = ?", "#{value.type_of_sport}").first.value %> </p>

                          <p> Date: <%= value.date.to_formatted_s(:long) %> </p>
                          <p> Time: <%= value.time.to_formatted_s(:time) %> </p>
                          <p> Region: <%= value.tags.where("tag_id = ?", "#{value.region}").first.value %> </p>

                          <p> Location: <%= value.tags.where("tag_id = ?", "#{value.location}").first.value %> </p>
                          <% counter = 0 %>
                          <% value.attendings.each_with_index do |x, y| %>
                            <% if x.user_id == current_user.id %>
                            <%= link_to "Leave", leave_event_path(value), :method=> :delete, :class=>"btn btn-primary" %>
                            <% counter = 1 %>
                            <% elsif y == value.attendings.length - 1 && counter == 0 %>
                            <%= link_to "Join Now!", join_event_path(value), :method=> :post, :class=>"btn btn-primary" %>
                            <% end %>
                          <% end %>
                           <%= link_to "More Info", event_path(value), { :class=>"btn btn-default" } %>
                      </div>
                  </div>
              </div>
          <% if index % 4 == 3 || @myevents.length - 1 == index %>
            </div>
          <% end %>
        <% end %>

        <hr>
        <% end %>
        <div class="col-lg-2" id="events">
          <%= calendar do |date| %>
            <%= link_to "#{date.day}", events_path(:date => "#{date}") %>
          <% end %>
        </div>
      </div>
      </div>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

    </div>

app/views/events/list.html.erb
<!-- Page Content -->
<div class="container">
    <!-- Page Heading -->
    <!-- /.row -->
  <div class="container">
    <ul class="nav nav-tabs">
      <li class="active" id="one"><%= link_to 'Latest Events', list_event_path, remote: true %></li>
        <% if current_user != nil %>
          <li id="two"><%= link_to 'Recommended Events', recommend_event_path, remote: true %></li>
          <li id="three"><%= link_to 'My Events', myevents_path, remote: true %></li>
        <% end %>
    </ul>
  </div>
    <div class="container" id="test">
      <%= render 'event' %>
    </div>
    <!-- Project One -->

    <!-- /.row -->


    <!-- Project Five -->

    <!-- Pagination -->
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">&laquo;</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">&raquo;</a>
                </li>
            </ul>
        </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
        <!-- /.row -->
    </footer>

</div>

app/views/events/list.js.erb
$("#one").removeClass('active');
$("#two").removeClass('active');
$("#three").removeClass('active');
if (<%= @check %> === 1) {
  $("#one").addClass('active');
} else if (<%= @check %> === 2) {
  $("#two").addClass('active');
} else if (<%= @check %> === 3) {
  $("#three").addClass('active');
}

$("#test").empty();
$("#test").append("<%= j render 'event' %>");

app/views/events/new.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Events#new</h1>
    <p>Find me in app/views/events/new.html.erb</p>
    <%= bootstrap_form_for :event, url: events_path do |p| %>
      <div class="row">
        <div class="col-md-6">
          <%= p.text_field :name, label: 'Name of Event', icon:'pencil' %>
        </div>
        <div class='col-md-2'>
          <!-- <%= p.text_field :region, label: 'Region', icon: 'map-marker' %> -->

          <%= p.collection_select :region, Tag.where("tag_category_id = ?", 0), :id, :value, label: 'Region' %>

        </div>
        <div class='col-md-2'>
          <!-- <%= p.text_field :location, label: 'Location', icon: 'map-marker' %> -->
          <%= p.collection_select :location, Tag.where("tag_category_id = ?", 1), :id, :value, label: 'Location' %>
        </div>
        <div class='col-md-2'>
          <!-- <%= p.text_field :type_of_sport, label: 'Type of Sport', icon: 'tags' %> -->
          <%= p.collection_select :type_of_sport, Tag.where("tag_category_id = ?", 2), :id, :value, label: 'Sports' %>
        </div>
        <div class='col-md-3'>
          <%= p.date_field :date, label: 'Date of Event', icon: 'calendar' %>
        </div>
        <div class='col-md-3'>
          <%= p.time_field :time, label: 'Time of Event', icon: 'time' %>
        </div>
        <div class='col-md-2'>
          <%= p.text_field :duration, label: 'Duration of Event', placeholder: 'E.g. 2 Hours', icon: 'hourglass' %>
        </div>
        <div class='col-md-2'>
          <%= p.text_field :minpax, label: 'Minimum Pax', icon: 'user' %>
        </div>
        <div class='col-md-2'>
          <%= p.text_field :maxpax, label: 'Maximum Pax', icon: 'user' %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= p.text_area :description, label: 'Description', icon:'list-alt', rows: "5" %>
        </div>
      </div>
        <%= p.submit class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="jumbotron" style="border-radius: 20px">
  <div class="container-fluid text-center">
    <div class="row content">
      <div class="col-sm-2 sidenav">
        <h3><%= link_to "Attendees", users_path(:search => @event.attendings.pluck(:user_id)) %></h3>
        <% @event.attendings.each do | value | %>
        <% User.all.where(id: value.user_id).first(5).each do | listuser | %>
        <%= link_to listuser.email, user_path(listuser.id) %>
        <% end %>
        <% end %>
      </div>
      <div class="col-sm-8 text-left">
        <h1><%= @event.name %></h1>
        <% @event.tags.where(id: @event.type_of_sport).each do |sport| %>
        <h2><%= sport.value %></h2>
        <% end %>
        <% @event.users.where(id: @event.user_id).each do |value| %>
        <li>Host: <%=value.email%> </li>
        <% end %>
        <li>Date: <%= @event.date.to_formatted_s(:long) %></li>
        <li>Time: <%= @event.time.to_formatted_s(:time) %></li>
        <li>Region: <%= @event.region %></li>
        <li>Location: <%= @event.location %></li>
        <% if @event.minpax == 0 %>
        <li>Max <%= @event.maxpax %> Pax</li>
        <%else%>
        <li>Min <%= @event.minpax %> - Max <%= @event.maxpax %> Pax</li>
        <%end%>
        <li>Current Attending: <%= @event.attendings.length %></li>
        <% @event.attendings.each do | value | %>
        <% User.all.where(id: value.user_id).each do | listuser | %>
        <%= listuser.name %>
        <% end %>
        <% end %>
        <li>Remaining Slots: <%= @event.maxpax - @event.attendings.length %></li>
        <hr>
        <div class="row">
        <div class="col-md-6">
        <h3>Description</h3>
        <p><%= @event.description %></p>
      </div>
      <% @event.tags.where(id: @event.location).each do |location| %>

        <iframe width="400" height="400" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCJ_zKe_xdEQi-gZx-x61gXLRZ9WexJXF8&q=<%= location.value %>&zoom=16" allowfullscreen></iframe>
      <% end %>
        <div class="col-md-6">
          <% if current_user == nil %>
            <%= link_to "Join", join_event_path(@event), :method=> :post, :class=>"btn btn-primary" %>
          <% else %>
          <% if @event.attendings.where(user_id: current_user.id).empty? %>
            <% if @event.maxpax == @event.attendings.length %>
            <button class="btn btn-static">Full</button>
            <% else %>
            <%= link_to "Join", join_event_path(@event), :method=> :post, :class=>"btn btn-primary" %>
            <% end %>
          <%else%>
            <%= link_to "Leave", leave_event_path(@event), :method=> :delete, :class=>"btn btn-primary" %>
          <% end %>
          <% end %>
        </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <h3>
                <%= link_to "Comments:", "javascript:;", id: "comments-link" %>
            </h3>
            <section id="comments-section">
              <ol id="comments">
                <%= render @comments %>
              </ol>
              <%= render 'comments/form' %>


            </section>

          </div>
        </div>
      </div>
      <div class="col-sm-2 sidenav">
        <div class="well">
          <p>ADS</p>
        </div>
        <div class="well">
          <p>ADS</p>
        </div>
      </div>
    </div>
  </div>


  <footer class="container-fluid text-center">

  </footer>

</div>